# Generated by Django 5.1.2 on 2024-10-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Can',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('continent', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('sku', models.CharField(blank=True, max_length=20, null=True)),
                ('manufacturer', models.CharField(max_length=50)),
                ('main_color', models.CharField(max_length=20)),
                ('detail_color', models.CharField(max_length=20)),
                ('color_lid', models.CharField(max_length=20)),
                ('color_top', models.CharField(max_length=20)),
                ('logo_lid', models.BooleanField(default=False)),
                ('sugar_warning', models.BooleanField(default=False)),
                ('condition', models.IntegerField()),
                ('top_intact', models.BooleanField(default=True)),
                ('is_promotion', models.BooleanField(default=False)),
                ('promotion_name', models.CharField(blank=True, max_length=100, null=True)),
                ('promotion_details', models.TextField(blank=True, null=True)),
                ('bottle', models.BooleanField(default=False)),
                ('tasted', models.BooleanField(default=False)),
                ('top_notes', models.TextField(blank=True, null=True)),
                ('bottom_notes', models.TextField(blank=True, null=True)),
                ('img_front', models.CharField(max_length=100)),
                ('img_back', models.CharField(max_length=100)),
                ('img_back_2', models.CharField(max_length=100)),
                ('img_top', models.CharField(max_length=100)),
                ('is_gift', models.BooleanField(default=False)),
                ('friend_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gift_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
