# Generated by Django 5.1.2 on 2024-10-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_alter_can_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can',
            name='line',
            field=models.CharField(choices=[('BEAST', 'Beast'), ('ENERGY', 'Energy'), ('ESPRESSO', 'Espresso'), ('ICE TEA', 'Ice Tea'), ('JAVA', 'Java'), ('JUICE', 'Juice'), ('MAXX', 'Maxx'), ('NITRO', 'Nitro'), ('PUNCH', 'Punch'), ('REHAB', 'Rehab'), ('RESERVE', 'Reserve'), ('TOUR WATER', 'Tour Water'), ('ULTRA', 'Ultra')], default='Energy', max_length=50),
        ),
    ]
